### ISSUE TITLE
Fail to load all documents

### ISSUE THREAD

**Issue by Salohyy212** [hei-school/hei-admin-ui#518]
All the documents on the home page fail to load when you try to display them, and the certificate also fails to download.

**Comment by NyAndoMayah** [comment]
Hello @Salohyy212 😄. Thanks so much for giving us your feedback 🚀 

### How documents work in the web application:
Make sure you have a **good internet connection** for optimal use of the documents in the web application.

### School certificate download:
The download of the school certificate is in progress via the following PR: [https://github.com/hei-school/hei-admin-api/pull/418](https://github.com/hei-school/hei-admin-api/pull/418)

If you still have any feedback to give us, don't hesitate. 😃
