### ISSUE TITLE
Profil Pic

### ISSUE THREAD

**Issue by tahiry-dev** [hei-school/hei-admin-ui#519]
As I understand, I should be able to add my picture as a profile, but I cannot.

**Comment by GinoANJARASOA** [comment]
Morning,
my profile on the hei Admine site is not displayed

**Comment by GinoANJARASOA** [comment]
![Uploading gino.png…]()


here is another photo

**Comment by NyAndoMayah** [comment]
@tahiry-dev  You cannot upload your profile picture unless you are a manager. Thanks for your issue ! :)
